version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine

  prototype.rabiitmq:
    image: ${DOCKER_REGISTRY}prototyperabiitmq
    build:
      context: .
      dockerfile: Prototype.RabiitMq/Dockerfile
    depends_on:
      - rabbitmq 

  prototype.rabbitmq.publish:
    image: ${DOCKER_REGISTRY}prototyperabbitmqpublish
    build:
      context: .
      dockerfile: Prototype.RabbitMq.Publish/Dockerfile
    depends_on:
      - rabbitmq 


  apigateways:
    image: ${DOCKER_REGISTRY}apigateways
    build:
      context: .
      dockerfile: ApiGateWays/Dockerfile
    depends_on:
      - prototype.rabiitmq 
      - prototype.rabbitmq.publish 
      - rabbitmq 
